### ISSUE TITLE
Issue if Dock is positioned at right

### ISSUE THREAD

**Issue by aleixsr** [PepsRyuu/dock-window-preview#5]
Hi, this application is awesome if you have Dock at bottom:

![image](https://github.com/PepsRyuu/dock-window-preview/assets/11422299/3ef9818a-35a1-4d71-acad-5da1968df25f)

but if you have Dock at right (or at left) it shows preview oustside screen range:

![image](https://github.com/PepsRyuu/dock-window-preview/assets/11422299/e9d5635d-ed11-4556-b0d7-41f43a048668)

I hope it should be easy to fix.

Thanks.

**Comment by PepsRyuu** [comment]
Yeah, that's definitely one of the things I've been meaning to do for this. I mostly develop it for myself, and I have my dock at the bottom, so never really allocated any time for it. It should be relatively straightforward to implement I think. Let me see if I can quicky draw something up. 🤔

**Comment by PepsRyuu** [comment]
Added a new configuration option. Reinstall with the quick start script. 

```
{
    "layout": {
        "dock": "right"
    }
}
```

**Comment by aleixsr** [comment]
Wow, you're a crack!
Thank you so much!
