### ISSUE TITLE
Screenshots appear a little bit weird

### ISSUE THREAD

**Issue by aleixsr** [PepsRyuu/dock-window-preview#6]
Currently they appear to narrow:

![image](https://github.com/PepsRyuu/dock-window-preview/assets/11422299/4483db07-f41b-4c7d-a119-0afcde591804)

Maybe can be an option to set screenshots width?

Thanks!

**Comment by PepsRyuu** [comment]
Shouldn't be too difficult to introduce an option for this. I assume what you'd be looking for is maintaining the aspect ratio of the window and to center it inside the gap (horizontally and vertically depending on aspect ratio of the window)?

**Comment by aleixsr** [comment]
> Shouldn't be too difficult to introduce an option for this. I assume what you'd be looking for is maintaining the aspect ratio of the window and to center it inside the gap (horizontally and vertically depending on aspect ratio of the window)?

Yes exactlly, thank you very much!

**Comment by PepsRyuu** [comment]
Let me see what I can come up with!

**Comment by PepsRyuu** [comment]
Released in `0.0.8`.

In your config, set the new `layout.preview` option to `fit`.

**Comment by PepsRyuu** [comment]
Fixed a bug in relation to square windows not rendering correctly in `0.0.9`.

**Comment by aleixsr** [comment]
Working fine!
